"""Add linear_regression_models table

Revision ID: new_revision_id
Revises: 60269a665a4a
Create Date: 2024-07-21 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edd28e02357'
down_revision: Union[str, None] = '60269a665a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linear_regression_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('model', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index(op.f('ix_linear_regression_models_id'), 'linear_regression_models', ['id'], unique=False)
    op.create_index(op.f('ix_linear_regression_models_ticker'), 'linear_regression_models', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linear_regression_models_ticker'), table_name='linear_regression_models')
    op.drop_index(op.f('ix_linear_regression_models_id'), table_name='linear_regression_models')
    op.drop_table('linear_regression_models')
    # ### end Alembic commands ###
